# -*- coding: utf-8 -*-
"""Quiz1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1StvhUKaCvsSMAC3ZDJ-r0E6OliS1R0hh
"""

print("This is a quiz")